apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-deployment
  labels:
    app: ecommerce
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
      - name: ecommerce
        image: your-image:tag
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: jdbc:mysql://mysql-db:3306/ecommerce_db?useSSL=false
        - name: DATABASE_USERNAME
          value: your-username
        - name: DATABASE_PASSWORD
          value: your-password
---
apiVersion: admissionregistration.k8s.io/v1
kind: Service
metadata:
  name: ecommerce-service
spec:
  selector:
    app: ecommerce
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: LoadBalancer
